[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
  -DHUB75_WOKWI_SIM=1
lib_deps =
  mrcodetastic/ESP32 HUB75 LED MATRIX PANEL DMA Display
